import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { configuration } from '../server/config.mjs';
import { openSpace } from '../server/space.mjs';
import { Store } from '../server/store.mjs';
import { PracticeStore, practiceConfiguration, unavailableRealState } from '../server/practice.mjs';

test('practice persists separately, spends atomically, deduplicates retries and never affects real allocations', async t => {
 const root = await mkdtemp(join(tmpdir(), 'fomo-practice-'));
 const config = configuration({ FOMO_MODE: 'preview', FOMO_SPACE_ROOT: join(root, 'real') });
 const pc = practiceConfiguration(config, { FOMO_PRACTICE_SPACE_ROOT: join(root, 'practice') });
 const realSpace = await openSpace(config), practiceSpace = await openSpace(pc);
 t.after(async () => { await realSpace.close(); await practiceSpace.close(); await rm(root, { recursive: true, force: true }); });
 const real = new Store(realSpace.afs, config), practice = new PracticeStore(practiceSpace.afs, pc);
 await real.init(); await practice.init();
 const before = (await real.read()).state;
 const token = 'a'.repeat(64), other = 'b'.repeat(64);
 assert.equal((await practice.session(token)).balance, '1000');
 assert.equal((await practice.session(token)).grants, 1);
 assert.equal((await practice.session(other)).balance, '1000');
 const input = { amount: '1000', team: 'dogs', name: 'Practice human', requestId: randomUUID() };
 const results = await Promise.all([practice.donate(token, input, 1000), practice.donate(token, input, 1000)]);
 assert.equal(results[0].paymentId, results[1].paymentId);
 assert.equal(results[0].wallet.balance, '0');
 await assert.rejects(practice.donate(token, { ...input, amount: '1', requestId: randomUUID() }, 1500), /Not enough/);
 await assert.rejects(practice.donate(token, { ...input, team: 'kids' }, 1500), /different details/);
 const after = await practice.state(2000, token);
 assert.equal(after.community, '1000'); assert.equal(after.mode, 'practice'); assert.equal(after.currency, 'FUSD');
 assert.equal(after.round.endsAt, 601000); assert.equal(after.wallet.balance, '0');
 assert.equal(after.payment.recipient, ''); assert.equal(after.receipts.length, 0);
 assert.ok(after.teams.every(team => team.topUp === '0' && team.realDonation === '0'));
 assert.equal((await practice.state(2000, other)).wallet.balance, '1000');
 assert.ok(!JSON.stringify(after).includes(token));
 await practice.state(601001, token);
 const replay = await practice.donate(token, input, 602000);
 assert.equal(replay.wallet.balance, '0');
 assert.equal((await practice.state(602000)).round, null);
 const restored = new PracticeStore(practiceSpace.afs, pc); await restored.init();
 assert.equal((await restored.state(602000, token)).history[0].amount, '1000');
 assert.equal((await restored.refill(token)).balance, '1000');
 await assert.rejects(restored.refill(token), /remaining/);
 assert.deepEqual((await real.read()).state, before);
 assert.equal(unavailableRealState(config).community, '0');
 assert.equal(unavailableRealState(config).campaign.accepting, false);
});
